version: '3'
services:
  server:
    build:
      context: /../../mnt/c/Programming/pet_projects/what-should-i-do/server/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /../../mnt/c/Programming/pet_projects/what-should-i-do/server/:/app
      - /../../mnt/c/Programming/pet_projects/what-should-i-do/server/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
  client:
    build:
      context: /../../mnt/c/Programming/pet_projects/what-should-i-do/client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /../../mnt/c/Programming/pet_projects/what-should-i-do/client/:/app
      - /../../mnt/c/Programming/pet_projects/what-should-i-do/client/node_modules
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/what-should-i-do
volumes:
  mongo-data:
